"""
LLM provider interface.

This module defines the types and Protocol that every LLM provider must satisfy.
The rest of the application only ever imports from here — never from a provider
module directly.

Design notes
------------
- ``ChatMessage`` and ``LLMResponse`` are frozen dataclasses: immutable,
  hashable, printable, and require no dependencies beyond the standard library.
- ``LLMProviderProtocol`` is a structural Protocol (PEP 544).  Any class with
  the correct method signatures satisfies it without explicit inheritance.
  This keeps provider implementations independent of this module.
- ``@runtime_checkable`` allows ``isinstance(obj, LLMProviderProtocol)``
  checks in the factory and in tests.
"""

from dataclasses import dataclass
from enum import StrEnum
from typing import Protocol, runtime_checkable


class MessageRole(StrEnum):
    """Valid roles for a chat message."""

    system = "system"
    user = "user"
    assistant = "assistant"


@dataclass(frozen=True)
class ChatMessage:
    """
    A single message in a conversation.

    ``frozen=True`` makes instances immutable and hashable.
    Pass lists of these into any provider's ``chat()`` method.
    """

    role: MessageRole
    content: str


@dataclass(frozen=True)
class TokenUsage:
    """
    Token consumption reported by the model.

    Tracking these numbers is essential for cost estimation and
    for understanding context-window pressure.
    """

    prompt_tokens: int
    completion_tokens: int
    total_tokens: int


@dataclass(frozen=True)
class LLMResponse:
    """
    The typed result returned by every provider.

    Fields
    ------
    content
        The text generated by the model.
    model
        The exact model identifier that produced the response.
        Useful when the same provider offers several models.
    usage
        Token counts.  Use these to estimate cost and to log usage.
    latency_ms
        Wall-clock time from the moment the request left the client
        to the moment the full response was received.  Does not include
        time spent building the prompt or parsing the response.
    """

    content: str
    model: str
    usage: TokenUsage
    latency_ms: float


@runtime_checkable
class LLMProviderProtocol(Protocol):
    """
    Structural interface that every LLM provider must satisfy.

    Why a Protocol instead of an ABC?
    ----------------------------------
    ABCs require explicit inheritance.  Protocols use structural (duck) typing:
    any class with the correct method signatures satisfies the contract,
    regardless of its class hierarchy.  This means:

    - Provider implementations remain independent of this module.
    - Test doubles (mocks, fakes) work without inheritance.
    - The interface can evolve without forcing changes to all providers.

    Implementing classes must provide both sync and async variants because:
    - Sync: useful in scripts, CLI tools, and tests.
    - Async: required for FastAPI endpoints and concurrent workloads.
    """

    def chat(self, messages: list[ChatMessage]) -> LLMResponse:
        """Send messages and return the model's response (synchronous)."""
        ...

    async def achat(self, messages: list[ChatMessage]) -> LLMResponse:
        """Send messages and return the model's response (asynchronous)."""
        ...
